### ISSUE TITLE
print shorthand ? stops outline view from updating

### ISSUE THREAD

**Issue by TheRoboZ** [japhib/pico8-ls#17]
If the current open document or any of its includes uses pico's print shorthand ?STR, X, Y, [COL], the outline view is not populated or updated anymore. If you comment out the line or change it to a standard print function it works

**Comment by japhib** [comment]
Fixed with 0.4.2

**Comment by TheRoboZ** [comment]
I just tried but it's still happening to me. I Not sure what warning this was giving but it stops the outline view from populating, even if the ? print is in an included file.

**Comment by japhib** [comment]
The outline view populates fine for me when there’s a ? print statement — can you provide more information to help me reproduce? Like full file contents, what exactly are you typing, maybe a video of your screen to show me?

**Comment by japhib** [comment]
Looking at this a bit now, it appears that the parser is having issues with `?` when there is more than one argument. I had only tested it with one argument 🤦

**Comment by japhib** [comment]
Not fixed yet, looks like there's another issue that needs to be addressed. But I'm able to consistently repro the problem.

**Comment by japhib** [comment]
Hey, I believe I've fixed this! Just released 0.4.3 with the fix. Lmk if it's still not working.
